### ISSUE TITLE
Documentation should tell that a full clone of the repo is needed

### ISSUE THREAD

**Issue by imker25** [ap0llo/changelog#514]
Hello,

I just figured out that this tool runs into the error shown below when it's not running on a full clone of the repository:

 ```txt
INFORMATION - Loading commits
Unhandled exception. LibGit2Sharp.NotFoundException: object not found - no match for id (4f9b53155d97e9f38e720ad45b60cc72a06f5314)
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_revwalk_next(RevWalkerHandle walker) in /_/LibGit2Sharp/Core/Proxy.cs:line 2774
   at LibGit2Sharp.CommitLog.CommitEnumerator.MoveNext() in /_/LibGit2Sharp/CommitLog.cs:line 140
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Grynwald.ChangeLog.Git.GitRepository.GetCommits(Nullable`1 fromCommit, GitId toCommit) in /_/src/ChangeLog/Git/GitRepository.cs:line 52
   at Grynwald.ChangeLog.Tasks.LoadCommitsTask.Run(ApplicationChangeLog changeLog) in /_/src/ChangeLog/Tasks/LoadCommitsTask.cs:line 49
   at Grynwald.ChangeLog.Tasks.SynchronousChangeLogTask.RunAsync(ApplicationChangeLog changeLog) in /_/src/ChangeLog/Tasks/SynchronousChangeLogTask.cs:line 11
   at Grynwald.ChangeLog.Pipeline.ChangeLogPipeline.RunAsync() in /_/src/ChangeLog/Pipeline/ChangeLogPipeline.cs:line 40
   at Grynwald.ChangeLog.Program.RunAsync(GenerateCommandLineParameters commandlineParameters) in /_/src/ChangeLog/Program.cs:line 176
   at Grynwald.ChangeLog.Program.Main(String[] args) in /_/src/ChangeLog/Program.cs:line 46
   at Grynwald.ChangeLog.Program.<Main>(String[] args)
```

Since most CI Systems like GitHub Actions or GitLab Pipelines will not create a full clone but shallow clone with a depth around 10 by default, running the tool will cause the error above after a view commits. 

Because this is very unexpected I think a hint to this fact is needed in the documentation, so users can setup there CI jobs with a full clone before the error occurs.

**Comment by ap0llo** [comment]
You're right, this is becoming common, I'll include this in the docs.

Maybe there's even a way to show a more specific error message when changelog is working on a shallow clone

**Comment by imker25** [comment]
Thank you.
